# Exploration

## Import libraries

In [ ]:
import fastf1
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
session = fastf1.get_session(2024, 'Sao Paulo Grand Prix', 'R')
session.load()
session.laps

## Weather

In [37]:
weather_data = session.laps.get_weather_data()

In [40]:
weather_data.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:22.903000,22.2,86.0,927.4,True,27.3,0,0.4
1,0 days 00:01:22.903000,22.3,87.0,927.3,True,26.2,191,0.0
2,0 days 00:02:22.903000,22.1,86.0,927.4,True,26.4,182,0.8
3,0 days 00:03:22.906000,22.1,87.0,927.4,True,26.4,210,0.5
4,0 days 00:04:22.910000,22.1,87.0,927.3,True,26.2,0,0.4

In [39]:
weather_data = session.weather_data  # Access weather data for the session
weather_data.head()

,Time,AirTemp,Humidity,Pressure,Rainfall,TrackTemp,WindDirection,WindSpeed
0,0 days 00:00:22.903000,22.2,86.0,927.4,True,27.3,0,0.4
1,0 days 00:01:22.903000,22.3,87.0,927.3,True,26.2,191,0.0
2,0 days 00:02:22.903000,22.1,86.0,927.4,True,26.4,182,0.8
3,0 days 00:03:22.906000,22.1,87.0,927.4,True,26.4,210,0.5
4,0 days 00:04:22.910000,22.1,87.0,927.3,True,26.2,0,0.4

## Other

In [ ]:
session.car_data

fastest_lap = session.laps.pick_fastest()
car_data = fastest_lap.get_car_data().add_distance()

session.track_status.head()

session.total_laps

len(session.drivers) * session.total_laps # is larger since not all drivers did all laps


laps = session.laps  # Get all laps completed in the session
driver_laps = session.laps.pick_drivers(['VER'])  # Get laps for a specific driver (e.g., 'VER' for Max Verstappen)


max(driver_laps['LapNumber']) # completed all laps

In [75]:
results_df = session.results
results_df.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,CountryCode,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,NED,1.0,1,17.0,NaT,NaT,NaT,0 days 02:06:54.430000,Finished,26.0
31,31,E OCON,OCO,ocon,Alpine,0093cc,alpine,Esteban,Ocon,Esteban Ocon,...,FRA,2.0,2,4.0,NaT,NaT,NaT,0 days 00:00:19.477000,Finished,18.0
10,10,P GASLY,GAS,gasly,Alpine,0093cc,alpine,Pierre,Gasly,Pierre Gasly,...,FRA,3.0,3,13.0,NaT,NaT,NaT,0 days 00:00:22.532000,Finished,15.0
63,63,G RUSSELL,RUS,russell,Mercedes,27F4D2,mercedes,George,Russell,George Russell,...,GBR,4.0,4,2.0,NaT,NaT,NaT,0 days 00:00:23.265000,Finished,12.0
16,16,C LECLERC,LEC,leclerc,Ferrari,E80020,ferrari,Charles,Leclerc,Charles Leclerc,...,MON,5.0,5,6.0,NaT,NaT,NaT,0 days 00:00:30.177000,Finished,10.0

In [73]:
results_df.head().T

,1,31,10,63,16
DriverNumber,1,31,10,63,16
BroadcastName,M VERSTAPPEN,E OCON,P GASLY,G RUSSELL,C LECLERC
Abbreviation,VER,OCO,GAS,RUS,LEC
DriverId,max_verstappen,ocon,gasly,russell,leclerc
TeamName,Red Bull Racing,Alpine,Alpine,Mercedes,Ferrari
TeamColor,3671C6,0093cc,0093cc,27F4D2,E80020
TeamId,red_bull,alpine,alpine,mercedes,ferrari
FirstName,Max,Esteban,Pierre,George,Charles
LastName,Verstappen,Ocon,Gasly,Russell,Leclerc
FullName,Max Verstappen,Esteban Ocon,Pierre Gasly,George Russell,Charles Leclerc
HeadshotUrl,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...,https://media.formula1.com/d_driver_fallback_i...
CountryCode,NED,FRA,FRA,GBR,MON
Position,1.0,2.0,3.0,4.0,5.0
ClassifiedPosition,1,2,3,4,5
GridPosition,17.0,4.0,13.0,2.0,6.0
Q1,NaT,NaT,NaT,NaT,NaT
Q2,NaT,NaT,NaT,NaT,NaT
Q3,NaT,NaT,NaT,NaT,NaT
Time,0 days 02:06:54.430000,0 days 00:00:19.477000,0 days 00:00:22.532000,0 days 00:00:23.265000,0 days 00:00:30.177000
Status,Finished,Finished,Finished,Finished,Finished
Points,26.0,18.0,15.0,12.0,10.0

In [71]:
results_df.columns

Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points'],
      dtype='object')